
default_platform(:ios)

api_key = app_store_connect_api_key(
  key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
  issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
  key_content: ENV['APP_STORE_CONNECT_KEY_CONTENT_BASE64'],
  is_key_content_base64: true,
  duration: 1200,
)

platform :ios do
  desc "Setup Certificates"
  lane :certificates do
    setup_ci
    match(
      type: "appstore",
      readonly: is_ci,
      api_key: api_key
      )
  end
end


platform :ios do
  desc "Push build to TestFlight"
  lane :beta do
    upload_to_testflight( 
      api_key: api_key,
      ipa: "../build/ios/ipa/try_on_example.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
